### ISSUE TITLE
Two touches get counted as three on Windows Standalone

### ISSUE THREAD

**Issue by Plukers** [prime31/TouchKit#31]
On a Surface with Windows 8 Pro TouchKit doesn't detect gestures properly because it counts the first touch as a touch and a mousclick. 
Therefore, if you touch the screen with two fingers, three `_liveTouches` are counted. 

I solved this problem in my case by removing `UNITY_STANDALONE_WIN` from the preprocessor directives in `internalUpdateTouches`. 
However, this isn't a general solution because as to be expected the mouse input is ignored.

**Comment by prime31** [comment]
Unity unfortunately doesn't separate touch and mouse input which is why the
first touch gets duped. There isn't really a great solution since there is
no preprocessor directive that would address a touch screen desktop OS or
any definitive API that Unity provides to do that. What you did will work
fine on any touch screen desktop.


Mike
