### ISSUE TITLE
How to use TouchkitLite

### ISSUE THREAD

**Issue by mrsufgi** [prime31/TouchKit#32]
How should we use TouchkitLite?  Can we use it as a standalone?

**Comment by prime31** [comment]
It is meant to be used standalone. It's purpose to do the raw touch processing and converting mouse input to touch so that you can use just the touches for processing both mobile and desktop input. It doesn't contain any of the fancy gesture recognizers or DPI scaling system that normal TouchKit has.

Mike


On Aug 29, 2015, at 4:02 AM, Ori Avraham <notifications@github.com> wrote:

How should we use TouchkitLite? Can we use it as a standalone?
